#-------------------------------
# Site Settings
title: ML4LMS 
logo: '/images/logo_chem.png'
description: ML4LMS Workshop @ ICLR'24
color_scheme: light  # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Submissions'
      url: '/submissions/'
    - title: 'Prizes'
      url: '/prizes/'
    - title: 'Speakers'
      url: '/work/'
    - title: 'Agenda'
      url: '/agenda/'
#    - title: 'Organizers'
#      url: '/committees/'


#      submenu:
#      - url: '/contact/'
#        title: 'Steering Committee'
#      - url: '/elements/'
#        title: 'Organizing Committee'
#      - url: '/elements/'
#        title: 'Program Committee'


#-------------------------------
# Author Settings
author:
  author__name: ML4LMS 
  author__bio: ML4LMS aims to highlight translational machine learning research in biology and chemistry for real-world applications in life and materials science
  author__avatar: '/images/logo_chem.png'

social:
#- {icon: "ion-logo-twitter", link: "https://twitter.com"}
#- {icon: "ion-logo-facebook", link: "https://facebook.com"}
#- {icon: "ion-logo-instagram", link: "https://instagram.com"}
#- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
#- {icon: "ion-logo-github", link: "https://github.com"}
#- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: ML4LMS Workshop
  hero__subtitle: ICML'24 - July 26th, Vienna, Austria
  hero__description: ML4LMS aims to highlight translational machine learning research in biology and chemistry for real-world applications in life and materials science
  hero__image: "/images/vienna_austria.jpeg"


#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: Thank you to our sponsors!

logo__items:
  - name: RELATION
    link: "https://www.relationrx.com/"
    image: "/images/relation_logo.png"
    size: 100

  - name: IQCAPITAL
    link: "https://www.iqcapital.vc/"
    image: "/images/iq_capital.png"
    size: 100

  - name: NVIDIA
    link: "https://www.nvidia.com/en-gb/industries/healthcare-life-sciences/"
    image: "/images/nvidia_logo.png"
    size: 100

  - name: MICROSOFT
    link: "https://www.microsoft.com/en-us/research/lab/microsoft-research-ai4science/"
    image: "/images/msft_logo.png"
    size: 100

  - name: SANDBOXAQ
    link: "https://www.sandboxaq.com/"
    image: "/images/sandboxaq_logo.png"
    size: 100



#-------------------------------
# Newsletter
mailchimp:
  enable: true
  mailchimp__identifier: https://bio.us22.list-manage.com/subscribe/post?u=c11b5cdfac933324ba6b81e53&amp;id=b2be655647&amp;f_id=0045cbe1f0 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text: Your email address...
  mailchimp__button__text: Register Interest


#-------------------------------
# Work Settings
work:
  enable: true
  work__title: Featured Speakers
  work__description: Leading researchers from Industry and Academia will be at the workshop.


#-------------------------------
# Testimonials Section
testimonials:
  enable: true

testimonial__title: Steering Committee
testimonial__description: Leading the workshops' vision and steering the community.

testimonial__items:
  - name: "Andrea Vollkamer"
    image: "/images/org/vollkamer.jpg"
    designation: "University of Saarland"
    link: "https://scholar.google.com/citations?user=ksE3fxQAAAAJ&hl=en"
    content: "German bioinformatician & professor of Data-Driven Drug Design at Saarland Uni and associated researcher at Helmholtz Institute for Pharmaceutical Research Saarland."
  
  - name: "Aviv Regev"
    image: "/images/org/regev.jpg"
    designation: "Genentech"
    link: "https://en.wikipedia.org/wiki/Aviv_Regev"
    content: "Computational biologist & Executive VP of Genentech. Also a core member at Broad Institute and professor at Massachusetts Institute of Technology."
  
  - name: "Cecilia Clementi"
    image: "/images/org/clementi.jpg"
    designation: "FU Berlin"
    link: "https://scholar.google.com/citations?user=0na1SpQAAAAJ&hl=en"
    content :  "Professor of Chemistry & Biomolecular Engineering at Rice University. She is also a Senior Scientist at the Center for Theoretical Biological Physics and co-Director of the National Science Foundation Molecular Sciences Software Institute."

  - name: "Charlotte M. Deanne, MBE"
    image: "/images/org/deane.jpg"
    designation: "University of Oxford"
    link: "https://en.wikipedia.org/wiki/Charlotte_Deane"
    content :  "Prof. of Structural Bioinformatics at University of Oxford and former Head of Statistics. Currently serving as the Executive Chair of the Engineering and Physical Sciences Research Council."

  - name: "Christian Dallago"
    image: "/images/org/dallago.JPG"
    designation: "NVIDIA, TU Munich"
    link: "https://scholar.google.com/citations?user=4q0fNGAAAAAJ&hl=en"
    content : "Chris is a computer scientist turned bioinformatician focusing on protein sequence representation learning. He is dedicated to addressing problems with scarce data, particularly in designing new proteins for therapeutic or industrial applications."

  - name: "Francesca Grisoni"
    image: "/images/org/grisoni.jpg"
    designation: "TU/Eindhoven"
    link: "https://scholar.google.com/citations?user=qw2NmGsAAAAJ&hl=en"
    content : "Assistant Professor in the Department of Biomedical Engineering at TU/Eindhoven, leading the Molecular Machine Learning team. Her research primarily centres on developing novel artificial intelligence methods for drug discovery, integrating computation and experimental validation in the wet-lab."

  - name: "Kevin Yang"
    image: "/images/org/yang.jpg"
    designation: "Microsoft Research"
    link: "https://scholar.google.com/citations?user=mq-Vzk8AAAAJ&hl=en"
    content : "Kevin Yang is a senior researcher at Microsoft Research in Cambridge, MA, focusing on problems at the intersection of machine learning and biology. He obtained his PhD from Caltech under Frances Arnold's supervision, specializing in applying machine learning to protein engineering."

  - name: "Marwim Segler"
    image: "/images/org/segler.jpg"
    designation: "Microsoft Research"
    link: "https://scholar.google.co.uk/citations?user=imsL94QAAAAJ&hl=en"
    content :  "Marwin Segler is a team lead at Microsoft Research AI4Science, specialising in chemistry, drug discovery, and machine learning. Prior to his current role, he worked at BenevolentAI (London) and obtained his PhD in chemistry from the University of Muenster."

  - name: "Nicholas Sofroniew"
    image: "/images/org/sofroniew.jpg"
    designation: "Chan Zuckerberg Initiative"
    link: "https://scholar.google.com/citations?user=lHhmCFAAAAAJ&hl=en"
    content : "Nicholas leads the imaging technology team at the Chan Zuckerberg Initiative, focused on developing new imaging technology for measuring biology in action. He has a background in systems neuroscience and mathematics, and was previously a researcher at the Janelia Research Campus."
    
  - name: "Peter Koo"
    image: "/images/org/koo.jpg"
    designation: "Cold Spring Harbor Laboratory"
    link: "https://scholar.google.com/citations?user=zoAsQGwAAAAJ&hl=en"
    content : "Peter K. Koo is an academic researcher at Cold Spring Harbor Laboratory, with contributions to interpretability & medicine research. He has an h-index of 13, co-authored 39 publications receiving 579 citations. Previous affiliations include Loyola Marymount University & Yale University."

  - name: "Pranam Chatterjee"
    image: "/images/org/chatterjee.jpg"
    designation: "Duke University"
    link: "https://scholar.google.co.uk/citations?user=XExgv9YAAAAJ&hl=en"
    content : "Assistant Professor of Biomedical Engineering and Computer Science at Duke University. His research focuses on generative AI and protein engineering for applications in genome, proteome, and cell engineering. A PhD graduate of the MIT Media Lab, he developed robust genome editing technologies using CRISPR enzymes."

  - name: "Rebecca K. Lindsey"
    image: "/images/org/lindsay.jpg"
    designation: "University of Michigan"
    link: "https://scholar.google.com/citations?user=S1kLwmQAAAAJ&hl=en"
    content : "Rebecca K. Lindsey is an Assistant Professor of Chemical Engineering at the University of Michigan. She also holds courtesy appointments in Applied Physics, Nuclear Engineering and Radiological Sciences, and Materials Science. Prior to joining UM, Dr. Lindsey led various research teams within the Energetic Materials Center at Lawrence Livermore National Laboratory."

  - name: "Ying Wai Li"
    image: "/images/org/waili.jpg"
    designation: "Los Alamos National Laboratory"
    link: "https://scholar.google.com/citations?user=6lSSrkEAAAAJ&hl=en"
    content : "a computational physicist, delves into algorithms and high-performance computing, exploring material properties and optimizing computer simulations. She's a specialist in thermodynamics and algorithm design, advancing research in both physics and computer science."

# Ogranizers Section
organizers:
  enable: true

organizers__title: Organizing Committee
organizers__description: Dedicated to community outreach, workshop logistics, and managing submissions & reviews.

organizers__items:
  - name: "Puck van Gerwen"
    image: "/images/org/gerwen.jpg"
    designation: "EPFL"
    link: "https://www.linkedin.com/in/puckvg/"
    content: "PhD student developing machine-learning models for molecules and chemical reactions"

  - name: "Charlie Harris"
    image: "/images/org/harris.jpg"
    designation: "University of Cambridge"
    link: "https://www.linkedin.com/in/charlie-harris-388285156/"
    content: "PhD Student at the Cambridge Centre for AI in Medicine. Working in Geometric Deep Learning and Structural Biology."

  - name: "Jinwoo Leem"
    image: "/images/org/leem.jpg"
    designation: "Alchemab Therapeutics"
    link: "https://www.linkedin.com/in/jleem/"
    content: "Director of Machine Learning Alchemab Therapeutics. DPhil in Bioinformatics by the University of Oxford."

  - name: "Umberto Lupo"
    image: "/images/org/lupo.jpg"
    designation: "EPFL"
    link: "https://www.linkedin.com/in/ulupo/"
    content : "Post-doctoral Researcher, machine learning & computational biology. PhD Theoretical and Mathematical Physics"

  - name: "Michael Pieler"
    image: "/images/org/pieler.jpg"
    designation: "Stability AI"
    link: "https://www.linkedin.com/in/michaelpieler/"
    content: "LLM Research at Stability AI. Deep learning engineer with a biotechnology background."

  - name: "Bruno Trentini"
    image: "/images/org/trentini.png"
    designation: "NVIDIA"
    link: "https://www.linkedin.com/in/btrentini/"
    content: "Global Life Sciences Research Alliances Lead at NVIDIA. Interested in Geometric Deep Learning and Biomolecular design."

  - name: "Olivia Viessmann"
    image: "/images/org/viessmann.jpg"
    designation: "Flagship Pioneering"
    link: "https://www.linkedin.com/in/olivia-viessmann-75b00b156/"
    content: "Senior Machine Learning Scientist in the Pioneering Intelligence team, with a focus on biotech applications. "

  - name: "Ellen Zhong"
    image: "/images/org/zhong.jpg"
    designation: "Princeton University"
    link: "https://www.linkedin.com/in/zhonge/"
    content: "Assistant Professor of Computer Science at Princeton University. Interested in the Intersection of AI and Biology."

#-------------------------------
# Program Committee Section
programs:
  enable: true

programs__title: Program Committee
programs__description: Contributing to defining speakers, sponsors, the website and reviewing submissions.


#-------------------------------
# Blog Section
blog:
  enable: true

blog__settings:
  blog__title: Agenda
  blog__description: Full agenda includes panels, poster sessions, and talks in ML for Life and Material Science.




#-------------------------------
# Footer Settings
footer__background__image: "/images/vienna_bg.png"

#-------------------------------
# Contact Settings
contact:
  email: workshop@ml4lms.bio # Add your form_id
  description: If you have any questions, please do reach out to the organizers # Add a description of your form

# NOTE
# Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id